; Inno Setup 6 Script
; Generated by Installer Generator — do not edit manually.
; Regenerate: python -m installer → Build Installer
; https://jrsoftware.org/isinfo.php
;
; NOTE: Template uses custom delimiters (double brackets / percent-brackets)
;       for Jinja2 directives so that Inno Setup's own {…} constants pass through unchanged.

#define AppName      "USSwing"
#define AppVersion   "1.0.9"
#define AppPublisher "USSwing"
#define AppExeName   "USSwing.exe"

[Setup]
AppId={{\"D6B9F89F-1EE7-4D2C-AD41-3E8C29F0DD53\"}}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={autopf}\USSwing
DefaultGroupName=USSwing
LicenseFile=F:\USMarket_Backtesting\us_swing\assets\license.txt
SetupIconFile=F:\USMarket_Backtesting\installer\assets\icon.ico
OutputDir=F:\USMarket_Backtesting\installer\installer_output
OutputBaseFilename=USSwing_1.0.9_Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\icon.ico

MinVersion=10.0
PrivilegesRequired=admin
SetupLogging=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]

Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked


[Files]
; Recursively include everything from the packaged application directory
Source: "F:\USMarket_Backtesting\us_swing\dist\USSwing\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; App icon — copied into install dir so shortcuts can reference it directly
Source: "F:\USMarket_Backtesting\installer\assets\icon.ico"; DestDir: "{app}"; Flags: ignoreversion


[Icons]

Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\icon.ico"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"

Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\icon.ico"; Tasks: desktopicon



[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

; Silent install: pass /SILENT or /VERYSILENT on the command line
; Logging:        pass /LOG=<path> to capture install log to a file


; ── Auto-updater config written to the install directory at install time ──────
[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ConfigPath: String;
  Lines: TStringList;
begin
  if CurStep = ssPostInstall then
  begin
    ConfigPath := ExpandConstant('{app}\updater_config.json');
    Lines := TStringList.Create;
    try
      Lines.Add('{');
      Lines.Add('  "enabled": true,');
      Lines.Add('  "current_version": "{#AppVersion}",');
      Lines.Add('  "github_repo": "Nikghu/usswing",');
      Lines.Add('  "github_asset_pattern": "_Setup.exe",');
      Lines.Add('  "check_url": "",');
      Lines.Add('  "interval_hours": 24,');
      Lines.Add('  "verify_checksum": true,');
      Lines.Add('  "verify_signature": false');
      Lines.Add('}');
      Lines.SaveToFile(ConfigPath);
    finally
      Lines.Free;
    end;
  end;
end;

